const articlesFromWeb = [
  {
    title: "Техническое собеседование на фронтенд разработчика",
    content: "Успешное техническое собеседование на фронтенд разработчика – это прежде всего подготовка. Вот список материалов и советов, которые помогут.",
    category: "interview",
    linkTittle: "Техническое собеседование на фронтенд разработчика",
    href: "https://proglib.io/p/interview-frontend-dev",
    image: "",
  },
  {
    title: "Как успешно пройти любое техническое собеседование",
    content: "Сирадж Равал, разработчик, писатель и видеоблоггер, рассказывает как успешно пройти любое техническое собеседование в 5 шагов.",
    category: "interview",
    linkTittle: "Как успешно пройти любое техническое собеседование",
    href: "https://proglib.io/p/programming-interview-success",
    image: "",
  },
  {
    title: "Беспощадный Frontend-тест: уволься сам, если не наберешь 7 из 10!",
    content: "Думаешь, что уже познал все тайны фронтенда? Готов поставить на кон свою репутацию разработчика? Этот тест заставит тебя попотеть — здесь нет места для случайных правильных ответов.",
    category: "tests",
    linkTittle: "test frontehd javascript",
    href: "https://proglib.io/tests/besposhchadnyy-frontend-test-uvolsya-sam-esli-ne-naberesh-7-iz-10",
    image: "https://media.proglib.io/tests/2024/11/27/e6d6185e21e1a5e18920e6c464223341.jpg",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  {
    title: "Article 1",
    content: "This is the content of Article 1",
    category: "",
    linkTittle: "",
    href: "",
    image: "",
  },
  
];
